linters:
  # TODO: remove the `disable` section
  disable:
    - errcheck
    - ineffassign
    - staticcheck
    - unused
  enable:
    - godot
    - gofmt
    - goimports
    - misspell
    - whitespace
    - gci
linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/lxc/terraform-provider-incus)
  goimports:
    local-prefixes: github.com/lxc/terraform-provider-incus
