on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

name: Test
jobs:
  acceptance-tests:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        go-version:
          - "1.21"
        incus-version:
          - daily
          - stable

    env:
      TF_ACC: "1"
      GO111MODULE: "on"
      LXD_REMOTE: local
      LXD_ADDR: localhost
      LXD_PORT: 8443
      LXD_GENERATE_CLIENT_CERTS: "true"
      LXD_ACCEPT_SERVER_CERTIFICATE: "true"
      LXD_SCHEME: https

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Setup Incus from ${{ matrix.incus-version }} repository
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends --yes \
            zfsutils-linux \
            bind9-dnsutils \
            jq
          sudo apt-get remove --purge uidmap --yes
          sudo rm -f /etc/subuid /etc/subgid

          curl -sL https://pkgs.zabbly.com/get/incus-${{ matrix.incus-version }} | sudo sh
          sudo chmod 666 /var/lib/incus/unix.socket
          sudo incus admin init --auto --network-port="$LXD_PORT" --network-address="$LXD_ADDR"

          LXD_TOKEN=$(incus config trust add terraform --quiet)
          incus remote add localhost "${LXD_TOKEN}"

      - name: Configure OVN
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends --yes \
            ovn-host \
            ovn-central

          sudo ovs-vsctl set open_vswitch . \
            external_ids:ovn-remote=unix:/var/run/ovn/ovnsb_db.sock \
            external_ids:ovn-encap-type=geneve \
            external_ids:ovn-encap-ip=127.0.0.1

      - name: Install dependencies
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
      - run: |
          make test

  build-platforms:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        go-version:
          - "1.21"

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run GoReleaser in build mode to test all release platforms
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: build --snapshot

  check-lint:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        go-version:
          - "1.21"

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - run: make fmtcheck
      - run: make vet
      - run: make static-analysis
